### ISSUE TITLE
Ck2 Problem with Coat of Arms popping up

### ISSUE THREAD

**Issue by Ck2Bugsarenotcool** [ck2plus/CleanSlate#49] opened 2021-04-13 18:58 UTC
Hello, I hope you are having a great day. I have a big problem with Crusader Kings 2. Where the coat of arms of counties are popping up and don't go away when I press the religious map mode or any map mode. It is super frustrating, annoying  and it makes me sad since when I first installed the game I played it for weeks and this never happened. If you can help me. Thank you in advance.

(Some people said it is unfixable, I still have hope that it is fixable.) 
![Ck2bugs](https://user-images.githubusercontent.com/82471295/114605975-58e5f580-9ca3-11eb-9f37-23ba84b27655.png)

**Comment by randomTechneck** [comment] 2021-04-18 06:24
There's "cull_distance" in mapitems.gfx that'll remove them if the camera is so far from the map but I'm not seeing anything that removes them based on map mode. To be honest I want to say I think that's how it's always been and the intended behavior but I'm just getting back into the game after a long while and my memory isn't the best.

**Comment by schwarherz** [comment] 2021-07-11 17:10
I'm pretty sure this is hardcoded (and intended) vanilla behavior. I'm going to close this pending further information.

**Closed by schwarherz** 2021-07-11 17:10 UTC
Labels: bug, question
